# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-25 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('buyer', models.IntegerField(choices=[(0, '私物'), (1, '会社所有')], default=0)),
                ('genre', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('difficulty', models.IntegerField(choices=[(0, ''), (1, '初学者向け'), (2, '中級者向け'), (3, '上級者向け'), (4, 'その他')], default=0)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.User'),
        ),
    ]
